### ISSUE TITLE
sha1: Apple M1 build failures

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/asm-hashes#28]
As discovered on #27, the `aarch64` assembly for the `sha1` ~~and `sha2`~~ (edit: SHA-256 support added in #35) crates does not compile on macOS/M1:

```
Compiling sha2-asm v0.5.4
The following warnings were emitted during compilation:

warning: src/sha256_aarch64.S:64:2: error: ADR/ADRP relocations must be GOT relative
warning:  adrp x2, .K
warning:  ^
warning: src/sha256_aarch64.S:64:2: error: unknown AArch64 fixup kind!
warning:  adrp x2, .K
warning:  ^
warning: src/sha256_aarch64.S:65:2: error: unknown AArch64 fixup kind!
warning:  add x2, x2, :lo12:.K
warning:  ^

error: failed to run custom build command for `sha2-asm v0.5.4`
```

**Comment by tarcieri** [comment]
I wonder if we could cross-compile to `aarch64` on a (x86) macOS CI instance to test this...

**Comment by lonnylot** [comment]
I'm currently trying to install `fil-ocl-core` and this seems to be throwing an error.

Any update on this or any way I could help make progress?

**Comment by tarcieri** [comment]
@lonnylot for now the `asm` is incompatible with macOS/M4. If `fil-ocl-core` is enabling it, they should probably gate it on e.g. Linux/ARM64 targets

**Comment by lonnylot** [comment]
I'm not familiar with the term 'gate it'. Could you describe it a bit or provide something I could google on?

**Comment by tarcieri** [comment]
Note that overall I think the best way forward here on the M1 is to use stdarch to leverage the ARMv8 Cryptography Extensions, although unfortunately [due to a recent regression the necessary intrinsics are no longer exposed](https://github.com/rust-lang/stdarch/issues/1003)

**Comment by Byron** [comment]
The related issue [is now this one](https://github.com/rust-lang/stdarch/issues/1055) and a PR is in the making to clean it up. I am hoping that this will provide the required intrinsics to eventually get fast SHA1 on M1's.

**Comment by tarcieri** [comment]
FWIW, here is the assembly generated by a Rust wrapper for the ARMv8 Cryptography Extensions:

https://godbolt.org/z/P8oje3EfK

See also my comment here:

https://github.com/RustCrypto/asm-hashes/issues/5#issuecomment-812890980

**Comment by tarcieri** [comment]
I opened a tracking issue for `stdarch`-based intrinsic implementations of hash functions here, which is probably the best way to tackle this particular problem: https://github.com/RustCrypto/hashes/issues/257

**Comment by dignifiedquire** [comment]
Given that the intrinsic solution is still a little out there, could we add a second aarch64 implementation for M1 here?

**Comment by tarcieri** [comment]
Yeah, that's why I provided the assembly output above, unless someone knows of something better for this purpose.
