### ISSUE TITLE
Wrap assembly from KeccakCodePackage

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/asm-hashes#3]
[KeccakCodePackage](https://github.com/gvanas/KeccakCodePackage/) provides optimized assembly for various platform, which will allow us to get significant speed-up for algorithms based on Keccak functions.

**Comment by tarcieri** [comment]
Ooh

**Comment by newpavlov** [comment]
We decided to deprecate these crates. We could add ASM backends based on KeccakCodePackage code in future, but such PRs should be opened in the hashes/sponges repository.
