### ISSUE TITLE
sha-1: asm fails to build on i686 and aarch64

### ISSUE THREAD

**Issue by jszwedko** [RustCrypto/asm-hashes#34]
Apologies, I'm unsure if this is specifically an issue with `hashes` or maybe has something to do with an interaction with [`cross`](https://github.com/rust-embedded/cross), but when I attempt to cross-compile to `aarch64-unknown-linux-gnu` it seems to chose invalid assembly instructions.

Part of the output of: 

```

   Compiling sha1-asm v0.4.4
The following warnings were emitted during compilation:

warning: src/x64.S: Assembler messages:
warning: src/x64.S:111: Error: unknown mnemonic `movq' -- `movq %rbx,%xmm0'
warning: src/x64.S:112: Error: unknown mnemonic `movq' -- `movq %rbp,%xmm1'
warning: src/x64.S:113: Error: unknown mnemonic `subq' -- `subq $64,%rsp'
warning: src/x64.S:116: Error: unknown mnemonic `movq' -- `movq %rdi,%r8'
warning: src/x64.S:117: Error: unknown mnemonic `movl' -- `movl 0(%rdi),%eax'
warning: src/x64.S:118: Error: unknown mnemonic `movl' -- `movl 4(%rdi),%ebx'
warning: src/x64.S:119: Error: unknown mnemonic `movl' -- `movl 8(%rdi),%ecx'
warning: src/x64.S:120: Error: unknown mnemonic `movl' -- `movl 12(%rdi),%edx'
warning: src/x64.S:121: Error: unknown mnemonic `movl' -- `movl 16(%rdi),%ebp'
warning: src/x64.S:122: Error: unknown mnemonic `movq' -- `movq %rsi,%rdi'
```

See full output here along with Cargo.toml and src/main.rs here: https://gist.github.com/jszwedko/9d0cfb8db04fdeffb83cae1f1e2acec4

**Comment by newpavlov** [comment]
We decided to deprecate the asm-hashes crates. Future ASM backends will be implemented using inline asm, hopefully the discussed problem will not apply to them.
