### ISSUE TITLE
Add a RISCV implementation

### ISSUE THREAD

**Issue by piegamesde** [RustCrypto/asm-hashes#43]
Currently, the software implementation of sha256 suffers from [a performance bug in code generation](https://github.com/RustCrypto/hashes/issues/328) on RISC-V targets. Additionally, I think that a target-specific implementation has a lot of potential for improvement compared to the current generic implementation. (The generic implementation has a lot of manual loop unrolling and is primed for compiler autovectorization. RISC-V does not profit from these, as vector operations are still WIP. I suspect that a simpler implementation would have less register pressure and thus better performance, in addition to smaller code)

**Comment by newpavlov** [comment]
We would be happy to accept RISC-V implementations, but PRs should be open against the [hashes repository](https://github.com/RustCrypto/hashes).
