### ISSUE TITLE
Migrating to inline assembly (Rust 1.59)

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/asm-hashes#45]
With the forthcoming release of Rust 1.59 at the end of February, which stabilizes inline assembly, I think it's time to start planning on eventually retiring this repo and migrating to inline assembly instead.

This should simplify a number of things like linking, testing, and overall crate/repo structure.

**Comment by roblabla** [comment]
Would you accept a PR adding a feature enabling inline asm? The use-case is that I'm cross-compiling stuff, and having a working assembler for some of the platforms I target is painful. Using rustc's built-in support for assembly would mean less moving parts for me.

**Comment by newpavlov** [comment]
Yes, but the PR would have to be opened against the hashes repository, not this one. To prevent breakage, inline assembly impl should be behind its own feature (e.g. `inline-asm`) until the next breaking release.

**Comment by newpavlov** [comment]
Going to close this issue since we decided to deprecate these crates and implement ASM backands directly in the hash crates.
