### ISSUE TITLE
md5 `thread 'main' has overflowed its stack`

### ISSUE THREAD

**Issue by MaxKingPor** [RustCrypto/asm-hashes#62]
* Compiling md5-asm with clang appears `thread 'main' has overflowed its stack`
`md-5 = { version = "0.10.5", features = ["oid", "asm"] }`
```
[env]
CC = "clang"

```
```
clang version 16.0.0
Target: x86_64-pc-windows-msvc
Thread model: posix
```
# Example
``` Rust
use ::md5::{Digest, Md5};

fn main() {
    println!("start md5");
    let mut m5: Md5 = Md5::new();
    m5.update(
        b"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    );
    println!("{:x}", m5.finalize())
}
```

**Comment by tarcieri** [comment]
While we could try to find a fix specific to this issue, our long-term plan is to migrate to inline ASM (#45) in order to mitigate all of these environment-specific concerns around inline ASM

**Comment by newpavlov** [comment]
Can you check whether https://github.com/RustCrypto/asm-hashes/pull/61 helps? Otherwise, the `asm-hashes`  crates do not quite work on Windows and effectively are in a semi-deprecated state.

**Comment by mati865** [comment]
I think this might not work with MSVC, mentioned PR fixes it for GNU which has slightly different ABI.

**Comment by tarcieri** [comment]
Oh right, we have a tracking issue for MSVC: #17

**Comment by newpavlov** [comment]
Closing as dup of #17.
